export const clothesProducts = [
  {
    id: "orange-cropped-t-shirt",
    imageId: 8148577,
    name: "Orange Cropped T-Shirt (Women)",
    price: `€ ${14.99}`,
    category: "tops",
  },
  {
    id: "dark-blue-t-shirt",
    imageId: 22441317,
    name: "Dark Blue T-Shirt",
    price: `€ ${19.99}`,
    category: "tops",
  },
  {
    id: "white-t-shirt",
    imageId: 20669538,
    name: "White T-Shirt (Men)",
    price: `€ ${24.99}`,
    category: "tops",
  },
  {
    id: "white-hoodie",
    imageId: 8217415,
    name: "White Hoodie (Men)",
    price: `€ ${39.99}`,
    category: "tops",
  },
  {
    id: "beige-casual-shirt",
    imageId: 22441291,
    name: "Beige Casual Shirt (Women)",
    price: `€ ${34.99}`,
    category: "tops",
  },
  {
    id: "gray-hoodie-w",
    imageId: 6311642,
    name: "Gray Hoodie (Women)",
    price: `€ ${39.99}`,
    category: "tops",
  },
  {
    id: "red-jacket",
    imageId: 9286317,
    name: "Red Jacket (Women)",
    price: `€ ${54.99}`,
    category: "tops",
  },
  {
    id: "casual-hoodie",
    imageId: 6311670,
    name: "Casual Hoodie (Men)",
    price: `€ ${44.99}`,
    category: "tops",
  },
  {
    id: "white-hooded-sportswear",
    imageId: 6311449,
    name: "White Hooded Sportswear (Men)",
    price: `€ ${39.99}`,
    category: "tops",
  },
  {
    id: "black-hoodie",
    imageId: 6311628,
    name: "Black Hoodie (Men)",
    price: `€ ${39.99}`,
    category: "tops",
  },
];

export const bottomProducts = [
  {
    id: "beige-casual-pants",
    imageId: 19456438,
    name: "Beige Casual Pants (Women)",
    price: `€ ${34.99}`,
    category: "bottoms",
  },
  {
    id: "brown-pants",
    imageId: 6727414,
    name: "Brown Pants (Men)",
    price: `€ ${34.99}`,
    category: "bottoms",
  },
  {
    id: "green-pants",
    imageId: 13125260,
    name: "Green Pants (Women)",
    price: `€ ${36.99}`,
    category: "bottoms",
  },
  {
    id: "green-denim-jeans",
    imageId: 11716437,
    name: "Green Denim Jeans (Men)",
    price: `€ ${39.99}`,
    category: "bottoms",
  },
  {
    id: "denim-jeans",
    imageId: 9775494,
    name: "Denim Jeans (Men)",
    price: `€ ${42.99}`,
    category: "bottoms",
  },
  {
    id: "casual-black-sweatpants",
    imageId: 33055598,
    name: "Casual Black Sweatpants (Men)",
    price: `€ ${39.99}`,
    category: "bottoms",
  },
  {
    id: "green-sweatpants",
    imageId: 33055635,
    name: "Green Sweatpants (Men)",
    price: `€ ${34.99}`,
    category: "bottoms",
  },
  {
    id: "light-wash-denim-pants",
    imageId: 19995459,
    name: "Light Wash Denim Pants (Women)",
    price: `€ ${42.99}`,
    category: "bottoms",
  },
  {
    id: "green-palm-print-pants",
    imageId: 19995460,
    name: "Green Palm-Print Pants (Women)",
    price: `€ ${44.99}`,
    category: "bottoms",
  },
  {
    id: "beige-wide-leg-pants",
    imageId: 17135748,
    name: "Beige Wide‑Leg Pants (Women)",
    price: `€ ${42.99}`,
    category: "bottoms",
  },
];
