export const spotlightProducts = [
  {
    id: "nba-finals-cap",
    imageId: 25561929,
    name: "NBA Finals Cap",
    price: `€ ${29.99}`,
    category: "home",
  },
  {
    id: "black-t-shirt-m",
    imageId: 8532616,
    name: "Black T-Shirt (Men)",
    price: `€ ${24.99}`,
    category: "home",
  },
  {
    id: "black-t-shirt-w",
    imageId: 4066292,
    name: "Black T-Shirt (Women)",
    price: `€ ${24.99}`,
    category: "home",
  },
  {
    id: "caramel-pants",
    imageId: 8609111,
    name: "Caramel pants",
    price: `€ ${59.99}`,
    category: "home",
  },
  {
    id: "nike-leather-shoes",
    imageId: 8957613,
    name: "Nike leather shoes",
    price: `€ ${129.99}`,
    category: "home",
  },
  {
    id: "black-&-yellow-air-jordans",
    imageId: 10195371,
    name: "Black & Yellow Air Jordans",
    price: `€ ${159.99}`,
    category: "home",
  },
  {
    id: "black-&-white-nikes",
    imageId: 1478442,
    name: "Black & White Nikes",
    price: `€ ${119.99}`,
    category: "home",
  },
  {
    id: "gray-hoodie-m",
    imageId: 6311719,
    name: "Gray Hoodie (Men)",
    price: `€ ${69.99}`,
    category: "home",
  },
  {
    id: "black-organizer-bag",
    imageId: 842959,
    name: "Black organizer Bag",
    price: `€ ${45.0}`,
    category: "home",
  },
  {
    id: "blue-&-white-air-forces-1",
    imageId: 13288274,
    name: "Blue & White Air forces 1",
    price: `€ ${110.0}`,
    category: "home",
  },
];
